### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by waliarubal** [bizzehdee/System.Net.Torrent#16]
- Is their a link to this library's documentation? 
- If I need to use it to make a down loader or something, where shall I look for samples?
- Is this library .NET 5 compliant?
- Does this library work with Windows, Mac and Linux?

**Comment by bizzehdee** [comment]
There is no documentation for the library right now, there is also no real world usable demo as the library is meant as a developer tool. Though there is a demo in the feature/utp branch, but that branch is not currently stable and the api within the library is subject to change.

Yes the library is .NET 5 compliant and will work on windows mac and linux as it is .net standard
