### ISSUE TITLE
UDP Tracker Scrape

### ISSUE THREAD

**Issue by hollow87** [bizzehdee/System.Net.Torrent#4]
It seems the code for UDP tracker scrape doesn't work properly as the responses are just the exception "Invalid response from tracker".

Upon further investigation it seems its an issue with the endianness.
In the file UDPTrackerClient.cs you pack the trasactionId without regard for endianness which on x86/x64 is little endian then when you unpack the trasactionId from the response into recTrasactionId you unpack it in Big Endian.

**Comment by bizzehdee** [comment]
this has now been resolved
