### ISSUE TITLE
Is there a way to save torrent files?

### ISSUE THREAD

**Issue by kris-g** [bizzehdee/System.Net.Torrent#5]
I see you can make a Metadata object from file. Would it be possible to implement creating it from a MagnetLink and then having a save method for creating a torrent file?

**Comment by bizzehdee** [comment]
This project had been dropped as i no longer had any need for it. I have come back to it over the last few days and will be doing some tidying up and adding torrent file read/write.

**Comment by bizzehdee** [comment]
You would want to use https://github.com/bizzehdee/System.Net.Torrent/blob/master/bencode/BencodingUtils.cs 

You would need to open a file stream, and encode to stream using the stream.
