### ISSUE TITLE
Wonderful - Anything but example

### ISSUE THREAD

**Issue by matteofabbri** [bizzehdee/System.Net.Torrent#7]
Seriusoly this project is wonderful, but can you add a very small example on on to use it ?

**Comment by Atulin** [comment]
This. There's zero anything when it comes to documentation.

**Comment by chez14** [comment]
Anyone want to start to contribute?

**Comment by bizzehdee** [comment]
96362c8c1632bc82df1b8ab2f207516aadc1ff17
